//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTypes
    {
        public int ID { get; set; }
        public Nullable<int> DetailOrder { get; set; }
        public string DetailEnglish { get; set; }
        public string DetailDutch { get; set; }
        public string DetailFrench { get; set; }
        public string DetailGerman { get; set; }
        public string DetailItalian { get; set; }
        public string DetailPolish { get; set; }
        public string DetailSlowak { get; set; }
        public bool LocationFrom { get; set; }
        public bool LocationTo { get; set; }
        public bool LocationActivity { get; set; }
        public bool SingleOrder { get; set; }
        public bool MultipleOrder { get; set; }
        public bool ValidWorkingHours { get; set; }
        public bool ValidHours { get; set; }
    }
}
