//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmDepartmentMails
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public string LocalServiceManager { get; set; }
        public string LocalGeneralManager { get; set; }
        public string CompanyServiceManager { get; set; }
        public string CompanyLocalRepresentative { get; set; }
        public string CEO { get; set; }
        public string LocalSalesManager { get; set; }
    }
}
