//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmLevels
    {
        public int ID { get; set; }
        public bool Warranty { get; set; }
        public int AlarmLevel { get; set; }
        public int MonthsToEvaluate { get; set; }
        public int PartsOrders { get; set; }
        public int Interventions { get; set; }
        public int Calls { get; set; }
        public bool AllConditionsShouldBeMet { get; set; }
        public bool SimultanuousToBeConsideredAsOne { get; set; }
        public bool IncludeIBS { get; set; }
        public bool AllINterventions { get; set; }
        public bool AllParts { get; set; }
    }
}
