//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmActivities
    {
        public int ID { get; set; }
        public string Department { get; set; }
        public string SerialNumber { get; set; }
        public string ActivityType { get; set; }
        public int ActivityID { get; set; }
        public string ActivityCode { get; set; }
        public bool Warranty { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string CustomerName { get; set; }
        public string MachineType { get; set; }
        public string Country { get; set; }
    }
}
