//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarms
    {
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DateOfAlarm { get; set; }
        public int NumberOfPartsOrders { get; set; }
        public int NumberOfInterventions { get; set; }
        public int NumberOfCalls { get; set; }
        public int AlarmLevel { get; set; }
        public bool MailsSent { get; set; }
        public string Technology { get; set; }
    }
}
