//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedCosts
    {
        public int ID { get; set; }
        public int ImportID { get; set; }
        public string ImportIDString { get; set; }
        public int ServiceOrderID { get; set; }
        public int CostID { get; set; }
        public string CostIDString { get; set; }
        public double LoadPercentage { get; set; }
        public bool FullyAssigned { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> FSE { get; set; }
        public string IncludeExclude { get; set; }
        public int CostDetailsID { get; set; }
    }
}
