//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCategories
    {
        public int ID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string DetailEnglish { get; set; }
        public string DetailDutch { get; set; }
        public string DetailFrench { get; set; }
        public string DetailGerman { get; set; }
        public string DetailItalian { get; set; }
        public string DetailPolish { get; set; }
        public string DetailSlowak { get; set; }
        public string CostAccount { get; set; }
        public Nullable<bool> OnesServiceOrder { get; set; }
        public Nullable<bool> MultipleServiceOrder { get; set; }
        public Nullable<bool> FromToDates { get; set; }
    }
}
