//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayDetails
    {
        public int ID { get; set; }
        public int ImportID { get; set; }
        public string ImportIDString { get; set; }
        public System.DateTime DateOfDay { get; set; }
        public string StartTime { get; set; }
        public string StopTime { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public Nullable<int> TravelFrom { get; set; }
        public Nullable<int> TravelTo { get; set; }
        public Nullable<int> ServiceOrder { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> FSE { get; set; }
        public Nullable<int> DayType { get; set; }
    }
}
