//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPLNDataEntities : DbContext
    {
        public ERPLNDataEntities()
            : base("name=ERPLNDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Srv_ServiceOrders> Srv_ServiceOrders { get; set; }
        public DbSet<Srv_Calls> Srv_Calls { get; set; }
        public DbSet<ERPLN_ServiceOrders> ERPLN_ServiceOrders { get; set; }
        public DbSet<Srv_ServiceorderRegels> Srv_ServiceorderRegels { get; set; }
        public DbSet<TypeCode> TypeCode { get; set; }
    }
}
