//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterventionsEntities : DbContext
    {
        public InterventionsEntities()
            : base("name=InterventionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActivityTypes> ActivityTypes { get; set; }
        public DbSet<ServiceOrder> ServiceOrder { get; set; }
        public DbSet<AlarmActivities> AlarmActivities { get; set; }
        public DbSet<Machines> Machines { get; set; }
        public DbSet<AlarmLevels> AlarmLevels { get; set; }
        public DbSet<AssignedCosts> AssignedCosts { get; set; }
        public DbSet<CostCategories> CostCategories { get; set; }
        public DbSet<CostDetails> CostDetails { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<PaymentMethods> PaymentMethods { get; set; }
        public DbSet<DayDetails> DayDetails { get; set; }
        public DbSet<TravelLocations> TravelLocations { get; set; }
        public DbSet<HourGroups> HourGroups { get; set; }
        public DbSet<Invoicing> Invoicing { get; set; }
        public DbSet<ServiceorderCalculateDetails> ServiceorderCalculateDetails { get; set; }
        public DbSet<TaskGroups> TaskGroups { get; set; }
        public DbSet<Traveling> Traveling { get; set; }
        public DbSet<ServiceReport> ServiceReport { get; set; }
        public DbSet<TypeCode> TypeCode { get; set; }
        public DbSet<AlarmDepartmentMails> AlarmDepartmentMails { get; set; }
        public DbSet<AlarmSalesMail> AlarmSalesMail { get; set; }
        public DbSet<AlarmHistory> AlarmHistory { get; set; }
        public DbSet<Alarms> Alarms { get; set; }
        public DbSet<IndividualAlarmMails> IndividualAlarmMails { get; set; }
    }
}
