//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machines
    {
        public string SerialNumber { get; set; }
        public string SerialNumber2 { get; set; }
        public string Customer { get; set; }
        public string CustomerNumber { get; set; }
        public string StrippitCustomerNumber { get; set; }
        public string Country { get; set; }
        public string CountryAbbreviation { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string SerializedArticleGroup { get; set; }
        public string Technology { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
    }
}
