//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int ID { get; set; }
        public Nullable<int> SrvOrder { get; set; }
        public string Omschr20 { get; set; }
        public string Cluster { get; set; }
        public string Omschr21 { get; set; }
        public Nullable<int> Werknemer { get; set; }
        public string Naam1 { get; set; }
        public Nullable<int> VerkopenAanRel { get; set; }
        public string Naam2 { get; set; }
        public string ServiceArea { get; set; }
        public string Omschr1 { get; set; }
        public string Project { get; set; }
        public string Omschr2 { get; set; }
        public string Adres1 { get; set; }
        public string Adres2 { get; set; }
        public string Adres3 { get; set; }
        public string Adres4 { get; set; }
        public string Adres5 { get; set; }
        public string Adres6 { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string WorkCenter { get; set; }
        public string Omschr3 { get; set; }
        public string Contract { get; set; }
        public string Omschr4 { get; set; }
        public string OrderQuotation { get; set; }
        public string Omschr5 { get; set; }
        public string SrvCenter { get; set; }
        public string Omschr6 { get; set; }
        public Nullable<int> CoverageType { get; set; }
        public string Omschr7 { get; set; }
        public Nullable<int> SrvType { get; set; }
        public string Omschr8 { get; set; }
        public string OrderProcedure { get; set; }
        public string DiscountPolicy { get; set; }
        public string DiscountFromPriceBooks { get; set; }
        public Nullable<int> ActLineNr { get; set; }
        public string Omschr9 { get; set; }
        public string RefActivity { get; set; }
        public string Omschr10 { get; set; }
        public string Item { get; set; }
        public string SerialNr { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Appointment { get; set; }
        public Nullable<System.DateTime> EarliestStartTime { get; set; }
        public Nullable<System.DateTime> PlannedStartTime { get; set; }
        public string OrderTxt { get; set; }
        public string ActivityText { get; set; }
        public string CallText { get; set; }
        public string SolutionText { get; set; }
        public string Problem { get; set; }
        public string Omschr22 { get; set; }
        public Nullable<System.DateTime> EindeGarantie { get; set; }
        public string ActivityTextDetail { get; set; }
        public string CallTextDetail { get; set; }
        public string SolutionTextDetail { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Verwerking { get; set; }
        public string HandledBy { get; set; }
        public string ProdDesc { get; set; }
    }
}
