//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srv_Calls
    {
        public int ID { get; set; }
        public int CallNumber { get; set; }
        public Nullable<int> ParentCall { get; set; }
        public Nullable<int> ChildCall { get; set; }
        public Nullable<int> ServiceOrder { get; set; }
        public string SalesId { get; set; }
        public string SalesName { get; set; }
        public string CustomerServiceName { get; set; }
        public string ServiceDepartment { get; set; }
        public string SerianNumberMachine { get; set; }
        public string DetailMachine { get; set; }
        public string Contact { get; set; }
        public Nullable<System.DateTime> Warranty { get; set; }
        public string Priority { get; set; }
        public string BadFix { get; set; }
        public string Country { get; set; }
        public string Problem { get; set; }
        public string Solution { get; set; }
        public Nullable<System.DateTime> ImportedDateTime { get; set; }
        public string SupportAfdeling { get; set; }
        public string Supportmedewerker { get; set; }
        public string NaamCallmelder { get; set; }
    }
}
