//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srv_ServiceOrders
    {
        public int ID { get; set; }
        public int Serviceorder { get; set; }
        public string Department { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerReference { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public Nullable<int> ServiceNumber { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string TypeDetail { get; set; }
        public string Coverage { get; set; }
        public string CoverageDetail { get; set; }
        public Nullable<System.DateTime> LeadTime { get; set; }
        public string Pricelist { get; set; }
        public string PaymentConditions { get; set; }
        public string Currency { get; set; }
        public string ShippingID { get; set; }
        public string ShippingName { get; set; }
        public string ShippingConditions { get; set; }
        public string ShippingConditionsDetails { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> ImportDateTime { get; set; }
    }
}
