//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srv_ServiceorderRegels
    {
        public int ID { get; set; }
        public int ServiceOrder { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Regelnummer { get; set; }
        public string OrderRegelnummer { get; set; }
        public Nullable<int> ActiviteitRegelnummer { get; set; }
        public string Kosttype { get; set; }
        public string Artikel { get; set; }
        public string ArtikelOmschrijving { get; set; }
        public Nullable<decimal> Aantal { get; set; }
        public string KostComponent { get; set; }
        public string KostComponentOmschrijving { get; set; }
        public Nullable<System.DateTime> PlannedLeadTime { get; set; }
        public Nullable<decimal> Kostprijs { get; set; }
        public string SoortLevering { get; set; }
        public string Magazijn { get; set; }
        public Nullable<decimal> LaatsteHoeveelheid { get; set; }
        public Nullable<decimal> NagecalculeerdeHoeveelheid { get; set; }
        public Nullable<decimal> TotaleHoeveelheid { get; set; }
        public Nullable<decimal> NaleveringHoeveelheid { get; set; }
        public Nullable<System.DateTime> WerkelijkeLeadime { get; set; }
        public string ServiceOrderDetail { get; set; }
        public string UurLoonSoort { get; set; }
        public Nullable<decimal> TijdsHoeveelheid { get; set; }
        public string ReisSoort { get; set; }
        public Nullable<int> NacalculatieFrequentie { get; set; }
        public Nullable<decimal> TotaleVerkoopprijs { get; set; }
        public Nullable<decimal> TotaleKost { get; set; }
        public Nullable<decimal> ReparatieGarantieVerkoopprijs { get; set; }
        public Nullable<decimal> ReparatieGarantieKostprijs { get; set; }
        public Nullable<decimal> ContractVerkoopprijs { get; set; }
        public Nullable<decimal> ContractKostprijs { get; set; }
        public Nullable<decimal> SrvOffVerkoopprijs { get; set; }
        public Nullable<decimal> SrvOffKostprijs { get; set; }
        public Nullable<decimal> FcoVerkoopprijs { get; set; }
        public Nullable<decimal> FcoKostprijs { get; set; }
        public Nullable<decimal> OverigeVerkoopprijs { get; set; }
        public Nullable<decimal> OverigeKostprijs { get; set; }
        public Nullable<decimal> FactuurVerkoopprijs { get; set; }
        public Nullable<decimal> FactuurKostprijs { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> MutatieDatum { get; set; }
        public string FactuurNummer { get; set; }
        public string Mutatiesoort { get; set; }
        public Nullable<System.DateTime> FactuurDatum { get; set; }
        public Nullable<int> Korting { get; set; }
        public Nullable<decimal> KortingsBedrag { get; set; }
        public Nullable<decimal> FactuurBedrag { get; set; }
        public string Land { get; set; }
        public string DetailBTWCode { get; set; }
        public Nullable<System.DateTime> ImportedDateTime { get; set; }
    }
}
