//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alarms
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCode
    {
        public int ID { get; set; }
        public int TypeInt { get; set; }
        public string Type { get; set; }
        public string Department { get; set; }
        public string TypeOmschrijving { get; set; }
        public string TypeOmschrijvingF { get; set; }
        public string TypeOmschrijvingD { get; set; }
        public string TypeOmschrijvingI { get; set; }
        public string Dekking { get; set; }
        public Nullable<int> CodeDekking { get; set; }
        public string Groep { get; set; }
        public bool Warning { get; set; }
        public bool Warranty { get; set; }
        public bool IBS { get; set; }
    }
}
